#!/bin/bash

GIT_AUTHOR_NAME='Tom Bamford'
GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"

GIT_AUTHOR_EMAIL='tom@atplanet.co.za'
GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"

export GIT_AUTHOR_NAME GIT_COMMITTER_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_EMAIL

export EDITOR=vim

alias vi=vim
